[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
